INSERT INTO MARCA (MARCA) VALUES ('Toyota');
INSERT INTO MARCA (MARCA) VALUES ('Ford');
INSERT INTO MARCA (MARCA) VALUES ('Honda');
INSERT INTO MARCA (MARCA) VALUES ('Chevrolet');
INSERT INTO MARCA (MARCA) VALUES ('Volkswagen');
INSERT INTO MARCA (MARCA) VALUES ('BMW');
INSERT INTO MARCA (MARCA) VALUES ('Mercedes-Benz');
INSERT INTO MARCA (MARCA) VALUES ('Audi');
INSERT INTO MARCA (MARCA) VALUES ('Nissan');
INSERT INTO MARCA (MARCA) VALUES ('Hyundai');

INSERT INTO MODELO (MODELO) VALUES ('Civic');
INSERT INTO MODELO (MODELO) VALUES ('Corolla');
INSERT INTO MODELO (MODELO) VALUES ('Accord');
INSERT INTO MODELO (MODELO) VALUES ('Camry');
INSERT INTO MODELO (MODELO) VALUES ('Mustang');
INSERT INTO MODELO (MODELO) VALUES ('F-150');
INSERT INTO MODELO (MODELO) VALUES ('Cruze');
INSERT INTO MODELO (MODELO) VALUES ('Malibu');
INSERT INTO MODELO (MODELO) VALUES ('Golf');
INSERT INTO MODELO (MODELO) VALUES ('Passat');
INSERT INTO MODELO (MODELO) VALUES ('X5');
INSERT INTO MODELO (MODELO) VALUES ('3 Series');
INSERT INTO MODELO (MODELO) VALUES ('C-Class');
INSERT INTO MODELO (MODELO) VALUES ('E-Class');
INSERT INTO MODELO (MODELO) VALUES ('A4');
INSERT INTO MODELO (MODELO) VALUES ('Q5');
INSERT INTO MODELO (MODELO) VALUES ('Altima');
INSERT INTO MODELO (MODELO) VALUES ('Maxima');
INSERT INTO MODELO (MODELO) VALUES ('Elantra');
INSERT INTO MODELO (MODELO) VALUES ('Santa Fe');

INSERT INTO COR (COR) VALUES ('Branco');
INSERT INTO COR (COR) VALUES ('Preto');
INSERT INTO COR (COR) VALUES ('Prata');
INSERT INTO COR (COR) VALUES ('Azul');
INSERT INTO COR (COR) VALUES ('Vermelho');
INSERT INTO COR (COR) VALUES ('Verde');
INSERT INTO COR (COR) VALUES ('Amarelo');
INSERT INTO COR (COR) VALUES ('Cinza');
INSERT INTO COR (COR) VALUES ('Laranja');
INSERT INTO COR (COR) VALUES ('Marrom');
INSERT INTO COR (COR) VALUES ('Fantasia');



INSERT INTO VEICULO (PLACA, IDMARCA, IDMODELO, IDCOR, OCUPANTES, VGRAVE, VLEVE, VFATAL)
VALUES ('AAA1A111', 1, 1, 1, 4, 1, 0, 0);
INSERT INTO VEICULO (PLACA, IDMARCA, IDMODELO, IDCOR, OCUPANTES, VGRAVE, VLEVE, VFATAL)
VALUES ('BBB2B222', 2, 2, 2, 2, 0, 1, 0);
INSERT INTO VEICULO (PLACA, IDMARCA, IDMODELO, IDCOR, OCUPANTES, VGRAVE, VLEVE, VFATAL)
VALUES ('CCC3C333', 3, 3, 3, 5, 0, 0, 1);
INSERT INTO VEICULO (PLACA, IDMARCA, IDMODELO, IDCOR, OCUPANTES, VGRAVE, VLEVE, VFATAL)
VALUES ('DDD4D444', 4, 4, 4, 3, 1, 0, 0);
INSERT INTO VEICULO (PLACA, IDMARCA, IDMODELO, IDCOR, OCUPANTES, VGRAVE, VLEVE, VFATAL)
VALUES ('EEE5E555', 5, 5, 5, 2, 0, 1, 0);
INSERT INTO VEICULO (PLACA, IDMARCA, IDMODELO, IDCOR, OCUPANTES, VGRAVE, VLEVE, VFATAL)
VALUES ('FFF6F666', 6, 6, 6, 4, 0, 0, 1);
INSERT INTO VEICULO (PLACA, IDMARCA, IDMODELO, IDCOR, OCUPANTES, VGRAVE, VLEVE, VFATAL)
VALUES ('GGG7G777', 7, 7, 7, 3, 1, 0, 0);
INSERT INTO VEICULO (PLACA, IDMARCA, IDMODELO, IDCOR, OCUPANTES, VGRAVE, VLEVE, VFATAL)
VALUES ('HHH8H888', 8, 8, 8, 5, 0, 1, 0);
INSERT INTO VEICULO (PLACA, IDMARCA, IDMODELO, IDCOR, OCUPANTES, VGRAVE, VLEVE, VFATAL)
VALUES ('III9I999', 9, 9, 9, 2, 0, 0, 1);
INSERT INTO VEICULO (PLACA, IDMARCA, IDMODELO, IDCOR, OCUPANTES, VGRAVE, VLEVE, VFATAL)
VALUES ('JJJ0J000', 10, 10, 10, 4, 1, 0, 0);
INSERT INTO VEICULO (PLACA, IDMARCA, IDMODELO, IDCOR, OCUPANTES, VGRAVE, VLEVE, VFATAL)
VALUES ('KKK1K111', 1, 1, 1, 3, 0, 1, 0);
INSERT INTO VEICULO (PLACA, IDMARCA, IDMODELO, IDCOR, OCUPANTES, VGRAVE, VLEVE, VFATAL)
VALUES ('LLL2L222', 2, 2, 2, 5, 0, 0, 1);
INSERT INTO VEICULO (PLACA, IDMARCA, IDMODELO, IDCOR, OCUPANTES, VGRAVE, VLEVE, VFATAL)
VALUES ('MMM3M333', 3, 3, 3, 4, 1, 0, 0);
INSERT INTO VEICULO (PLACA, IDMARCA, IDMODELO, IDCOR, OCUPANTES, VGRAVE, VLEVE, VFATAL)
VALUES ('NNN4N444', 4, 4, 4, 2, 0, 1, 0);
INSERT INTO VEICULO (PLACA, IDMARCA, IDMODELO, IDCOR, OCUPANTES, VGRAVE, VLEVE, VFATAL)
VALUES ('OOO5O555', 5, 5, 5, 3, 0, 0, 1);
INSERT INTO VEICULO (PLACA, IDMARCA, IDMODELO, IDCOR, OCUPANTES, VGRAVE, VLEVE, VFATAL)
VALUES ('PPP6P666', 6, 6, 6, 5, 1, 0, 0);
INSERT INTO VEICULO (PLACA, IDMARCA, IDMODELO, IDCOR, OCUPANTES, VGRAVE, VLEVE, VFATAL)
VALUES ('QQQ7Q777', 7, 7, 7, 4, 0, 1, 0);
INSERT INTO VEICULO (PLACA, IDMARCA, IDMODELO, IDCOR, OCUPANTES, VGRAVE, VLEVE, VFATAL)
VALUES ('RRR8R888', 8, 8, 8, 3, 0, 0, 1);
INSERT INTO VEICULO (PLACA, IDMARCA, IDMODELO, IDCOR, OCUPANTES, VGRAVE, VLEVE, VFATAL)
VALUES ('SSS9S999', 9, 9, 9, 2, 1, 0, 0);
INSERT INTO VEICULO (PLACA, IDMARCA, IDMODELO, IDCOR, OCUPANTES, VGRAVE, VLEVE, VFATAL)
VALUES ('TTT0T000', 10, 10, 10, 5, 0, 1, 0);

INSERT INTO VIA(PREFIXO, RODOVIA) VALUES('SP-010', 'Rodovia Anchieta');
INSERT INTO VIA(PREFIXO, RODOVIA) VALUES('SP-021', 'Rodovia Ayrton Senna');
INSERT INTO VIA(PREFIXO, RODOVIA) VALUES('SP-055', 'Rodovia Carvalho Pinto');
INSERT INTO VIA(PREFIXO, RODOVIA) VALUES('SP-070', 'Rodovia Castello Branco');
INSERT INTO VIA(PREFIXO, RODOVIA) VALUES('SP-075', 'Rodovia Dom Gabriel Paulino Bueno Couto');
INSERT INTO VIA(PREFIXO, RODOVIA) VALUES('SP-083', 'Rodovia Doutor João Mendes da Silva Junqueira');
INSERT INTO VIA(PREFIXO, RODOVIA) VALUES('SP-099', 'Rodovia dos Imigrantes');
INSERT INTO VIA(PREFIXO, RODOVIA) VALUES('SP-101', 'Rodovia dos Bandeirantes');
INSERT INTO VIA(PREFIXO, RODOVIA) VALUES('SP-125', 'Rodovia Floriano Rodrigues Pinheiro');
INSERT INTO VIA(PREFIXO, RODOVIA) VALUES('SP-148', 'Rodovia dos Trabalhadores');
INSERT INTO VIA(PREFIXO, RODOVIA) VALUES('SP-150', 'Rodovia Anhanguera');
INSERT INTO VIA(PREFIXO, RODOVIA) VALUES('SP-160', 'Rodovia Hélio Smidt');
INSERT INTO VIA(PREFIXO, RODOVIA) VALUES('SP-225', 'Rodovia Engenheiro João Baptista Cabral Rennó');
INSERT INTO VIA(PREFIXO, RODOVIA) VALUES('SP-270', 'Rodovia Raposo Tavares');
INSERT INTO VIA(PREFIXO, RODOVIA) VALUES('SP-270', 'Rodovia Castelo Branco');
INSERT INTO VIA(PREFIXO, RODOVIA) VALUES('SP-280', 'Rodovia Presidente Castelo Branco');
INSERT INTO VIA(PREFIXO, RODOVIA) VALUES('SP-330', 'Rodovia Anhanguera');
INSERT INTO VIA(PREFIXO, RODOVIA) VALUES('SP-333', 'Rodovia Engenheiro Paulo Nilo Romano');
INSERT INTO VIA(PREFIXO, RODOVIA) VALUES('SP-340', 'Rodovia Adhemar de Barros');
INSERT INTO VIA(PREFIXO, RODOVIA) VALUES('SP-348', 'Rodovia dos Bandeirantes');

INSERT INTO ACIDENTE (IDBO, IDVEICULO, DATA, IDVIA, SENTIDO, CLIMA, TRACADOVIA, VEICENVOLVIDO)
VALUES (5, 3, '2023-09-08', 1, 'N', 'C', 'R', 8);
INSERT INTO ACIDENTE (IDBO, IDVEICULO, DATA, IDVIA, SENTIDO, CLIMA, TRACADOVIA, VEICENVOLVIDO)
VALUES (2, 7, '2023-09-07', 2, 'S', 'N', 'C', 6);
INSERT INTO ACIDENTE (IDBO, IDVEICULO, DATA, IDVIA, SENTIDO, CLIMA, TRACADOVIA, VEICENVOLVIDO)
VALUES (8, 1, '2023-09-06', 3, 'L', 'S', 'A', 3);
INSERT INTO ACIDENTE (IDBO, IDVEICULO, DATA, IDVIA, SENTIDO, CLIMA, TRACADOVIA, VEICENVOLVIDO)
VALUES (4, 10, '2023-09-05', 4, 'O', 'C', 'R', 9);
INSERT INTO ACIDENTE (IDBO, IDVEICULO, DATA, IDVIA, SENTIDO, CLIMA, TRACADOVIA, VEICENVOLVIDO)
VALUES (9, 5, '2023-09-04', 5, 'N', 'S', 'D', 10);
INSERT INTO ACIDENTE (IDBO, IDVEICULO, DATA, IDVIA, SENTIDO, CLIMA, TRACADOVIA, VEICENVOLVIDO)
VALUES (7, 3, '2023-09-03', 6, 'L', 'C', 'A', 2);
INSERT INTO ACIDENTE (IDBO, IDVEICULO, DATA, IDVIA, SENTIDO, CLIMA, TRACADOVIA, VEICENVOLVIDO)
VALUES (3, 9, '2023-09-02', 7, 'S', 'N', 'C', 7);
INSERT INTO ACIDENTE (IDBO, IDVEICULO, DATA, IDVIA, SENTIDO, CLIMA, TRACADOVIA, VEICENVOLVIDO)
VALUES (1, 2, '2023-09-01', 8, 'O', 'S', 'R', 5);
INSERT INTO ACIDENTE (IDBO, IDVEICULO, DATA, IDVIA, SENTIDO, CLIMA, TRACADOVIA, VEICENVOLVIDO)
VALUES (6, 8, '2023-08-31', 9, 'N', 'C', 'D', 4);
INSERT INTO ACIDENTE (IDBO, IDVEICULO, DATA, IDVIA, SENTIDO, CLIMA, TRACADOVIA, VEICENVOLVIDO)
VALUES (10, 4, '2023-08-30', 10, 'L', 'N', 'A', 1);
INSERT INTO ACIDENTE (IDBO, IDVEICULO, DATA, IDVIA, SENTIDO, CLIMA, TRACADOVIA, VEICENVOLVIDO)
VALUES (5, 3, '2023-08-29', 1, 'N', 'C', 'R', 8);
INSERT INTO ACIDENTE (IDBO, IDVEICULO, DATA, IDVIA, SENTIDO, CLIMA, TRACADOVIA, VEICENVOLVIDO)
VALUES (2, 7, '2023-08-28', 2, 'S', 'N', 'C', 6);
INSERT INTO ACIDENTE (IDBO, IDVEICULO, DATA, IDVIA, SENTIDO, CLIMA, TRACADOVIA, VEICENVOLVIDO)
VALUES (8, 1, '2023-08-27', 3, 'L', 'S', 'A', 3);
INSERT INTO ACIDENTE (IDBO, IDVEICULO, DATA, IDVIA, SENTIDO, CLIMA, TRACADOVIA, VEICENVOLVIDO)
VALUES (4, 10, '2023-08-26', 4, 'O', 'C', 'R', 9);
INSERT INTO ACIDENTE (IDBO, IDVEICULO, DATA, IDVIA, SENTIDO, CLIMA, TRACADOVIA, VEICENVOLVIDO)
VALUES (9, 5, '2023-08-25', 5, 'N', 'S', 'D', 10);
INSERT INTO ACIDENTE (IDBO, IDVEICULO, DATA, IDVIA, SENTIDO, CLIMA, TRACADOVIA, VEICENVOLVIDO)
VALUES (7, 3, '2023-08-24', 6, 'L', 'C', 'A', 2);
INSERT INTO ACIDENTE (IDBO, IDVEICULO, DATA, IDVIA, SENTIDO, CLIMA, TRACADOVIA, VEICENVOLVIDO)
VALUES (3, 9, '2023-08-23', 7, 'S', 'N', 'C', 7);
INSERT INTO ACIDENTE (IDBO, IDVEICULO, DATA, IDVIA, SENTIDO, CLIMA, TRACADOVIA, VEICENVOLVIDO)
VALUES (1, 2, '2023-08-22', 8, 'O', 'S', 'R', 5);
INSERT INTO ACIDENTE (IDBO, IDVEICULO, DATA, IDVIA, SENTIDO, CLIMA, TRACADOVIA, VEICENVOLVIDO)
VALUES (6, 8, '2023-08-21', 9, 'N', 'C', 'D', 4);
INSERT INTO ACIDENTE (IDBO, IDVEICULO, DATA, IDVIA, SENTIDO, CLIMA, TRACADOVIA, VEICENVOLVIDO)
VALUES (10, 4, '2023-08-20', 10, 'L', 'N', 'A', 1);


